package com.cp.createtable;

public class CreateTable {
	
private static final String createNewsTable = "DROP TABLE IF EXISTS `news`;CREATE TABLE `news` (`ID` int(11) NOT NULL AUTO_INCREMENT,`time` varchar(30) DEFAULT NULL,`title` varchar(100) DEFAULT NULL,`imageOri` varchar(100) DEFAULT NULL,`imageThumbnail` varchar(100) DEFAULT NULL,`imageThumbnailUrl` varchar(200) DEFAULT NULL,`content` varchar(1024) DEFAULT NULL,`contentUrl` varchar(200) DEFAULT NULL,`abstract` varchar(200) DEFAULT NULL,`author` varchar(30) DEFAULT NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
private static final String createPushTable = "DROP TABLE IF EXISTS `push`;CREATE TABLE `push` (`ID` int(11) NOT NULL AUTO_INCREMENT,`time` varchar(30) DEFAULT NULL,`content` varchar(200) DEFAULT NULL,`tips` varchar(100) DEFAULT NULL,`abstract` varchar(200) DEFAULT NULL,`area` varchar(30) DEFAULT NULL,`object` varchar(30) DEFAULT NULL,`title` varchar(100) DEFAULT NULL,PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
private static final String createFeedbackTable = "DROP TABLE IF EXISTS `feedback`;CREATE TABLE `feedback` (`ID` int(11) NOT NULL,`time` varchar(30) DEFAULT NULL,`feedback` varchar(200) DEFAULT NULL,`uuId` varchar(200) DEFAULT NULL,`operation` bit(1) DEFAULT NULL,`telephone` varchar(15) DEFAULT NULL,PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
private static final String createExhibitionTable = "DROP TABLE IF EXISTS `exhibition`;CREATE TABLE `exhibition` (`ID` int(11) NOT NULL AUTO_INCREMENT,`time` varchar(30) DEFAULT NULL,`type` varchar(10) DEFAULT NULL,`oripath` varchar(100) DEFAULT NULL,`Url` varchar(200) DEFAULT NULL,`description` varchar(150) DEFAULT NULL,`thumbpath` varchar(255) DEFAULT NULL,PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
private static final String createAppsTable = "DROP TABLE IF EXISTS `apps`;CREATE TABLE `apps` (`ID` int(11) NOT NULL,`time` varchar(30) DEFAULT NULL,`title` varchar(100) DEFAULT NULL,`bigVersion` int(10) DEFAULT NULL,`mediumVersion` int(10) DEFAULT NULL,`smallVersion` int(10) DEFAULT NULL,`submit` varchar(100) DEFAULT NULL,`type` varchar(10) DEFAULT NULL,`description` varchar(150) DEFAULT NULL,`Url` varchar(200) DEFAULT NULL,PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
private static final String createAccountTable = "DROP TABLE IF EXISTS `account`;CREATE TABLE `account` (`ID` int(11) NOT NULL AUTO_INCREMENT,`userName` varchar(50) NOT NULL,`passwd` varchar(100) NOT NULL,PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
}
